spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myBank
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: myBank
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        logging.level.org.hibernate.SQL: DEBUG
        logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: health
hosts:
  authorization: https://run.mocky.io/v3/73dc322c-533c-4e9f-8d51-4cc8928332dc
info:
  db-status: "OK"
  app-status: "OK"
api:
  security:
    token:
      secret: abc




