spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybank
    username: root
    password: 97505020rk
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: myBank
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        logging.level.org.hibernate.SQL: DEBUG
        logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management:
  endpoints:
    web:
      exposure:
        include: health
hosts:
  authorization: https://run.mocky.io/v3/8fafdd68-a090-496f-8c9a-3442cf30dae6
info:
  db-status: "OK"
  app-status: "OK"
api:
  security:
    token:
      secret: abc




